version: "3"
services:
  db:
    image: postgres
    container_name: db_v2_test
    restart: always #container reinicia se morrer
    ports:
      - 2345:5432
    env_file:
      - .env #configurar POSTGRES_USER, POSTGRES_PASSWORD e POSTGRES_DB
    volumes:
      - postgres:/var/lib/postgresql/data

  node_app:
    container_name: node_app_v2_test
    build: . #Dockerfile do node se encontra na pasta atual
    ports:
      - 5000:5000
    depends_on:
      - db # sรณ sobe quando o postgres tiver no ar
    env_file:
      - .env.test #configurar DATABASE_URL
